apiVersion: apps/v1
kind: Deployment ## 디플로이먼트 버전을 포함할 필요가 없다.
metadata:
  name: kubia
spec:
  replicas: 3
  template:
    metadata:
      name: kubia
      labels:
        app: kubia
    spec:
      containers:
        - image: luksa/kubia:v1
          name: nodejs
  selector:
    matchLabels:
      app: kubia
